config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
    patch "/users/confirmation" => "confirmations#confirm"
  end
  resources :events, only: %i[index show new create edit update] do
    resources :notifications, only: %i[new create] do
      get :preview_email, on: :collection
    end
    resources :experiences, only: %i[index new create edit update] do
      resources :notifications, only: %i[show edit update] do
        get :preview_email, on: :member
        resources :guests_notifications, only: %i[new create destroy]
      end
    end
    resources :guests, only: %i[index new create edit update destroy]
  end
  resource :short_url, only: :show
  resource :end_user_agreement, only: :show
  resource :privacy_policy, only: :show
  resource :terms_and_conditions, only: :show
  get 'contact_us', to: 'contacts#new'
  resources :contacts, only: [:create]
  root to: 'events#index'
end

app/models/guest.rb
# frozen_string_literal: true

# guests of the top-level event
class Guest < ApplicationRecord
  belongs_to :event
  belongs_to :email_encrypted_field,
             class_name: 'EncryptedField',
             foreign_key: 'email_encrypted_field_id',
             inverse_of: :guests
  belongs_to :phone_number_encrypted_field,
             class_name: 'EncryptedField',
             foreign_key: 'phone_number_encrypted_field_id',
             inverse_of: :guests

  has_many :guests_notifications, dependent: :destroy
  has_many :notifications, through: :guests_notifications,
                           source: :notification

  enum notification_category: %i[text email both]

  validates :first_name,
            presence: true,
            if: proc { |guest| guest.last_name.blank? }
  validates :last_name,
            presence: true,
            if: proc { |guest| guest.first_name.blank? }
  validate :email_validator
  validate :phone_number_validator

  default_scope { order(last_name: :asc, first_name: :asc) }
  scope :not_related_to_notification,
        ->(notification) { where.not(id: notification.guests.map(&:id)) }

  after_create :send_welcome_notifications
  after_update :send_welcome_notifications, if: :needs_welcome?

  def email=(val)
    return unless val
    email_encrypted_field.blob = val
  end

  def email
    email_encrypted_field.blob
  end

  def email_encrypted_field
    super || build_email_encrypted_field
  end

  def phone_number=(val)
    value = val.blank? ? '' : val.gsub(/[^0-9]/, '')
    phone_number_encrypted_field.blob = value
  end

  def phone_number
    phone_number_encrypted_field.blob
  end

  def phone_number_encrypted_field
    super || build_phone_number_encrypted_field
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def pretty_notification_category
    if notification_category == 'both'
      'text, email'
    else
      notification_category
    end
  end

  def pretty_phone_number
    return unless phone_number
    "(#{phone_number[0..2]}) #{phone_number[3..5]}-#{phone_number[6..9]}"
  end

  private

  def email_validator
    emails = Guest.where.not(id: id).where(event_id: event_id).map(&:email)
    return unless emails.include?(email)
    errors.add(
      :email,
      '- It looks like the guest shares an email with another guest. ' \
      'If this is the case, please leave email blank.'
    )
  end

  def guest_phone_numbers
    Guest.where.not(id: id).where(event_id: event_id).map(&:phone_number)
  end

  def phone_number_validator
    return if phone_number.blank?
    if phone_number&.length != 10
      errors.add(:phone_number, 'must be 10 characters')
    end
    return unless guest_phone_numbers.include?(phone_number)
    errors.add(:phone_number, '- It looks like the guest shares a phone ' \
                              'number with another guest. If this is the ' \
                              'case, please leave phone number blank.')
  end

  def send_welcome_notifications
    Tasks::Notifier.send_first_notification(self)
  end

  def needs_welcome?
    return false unless saved_change_to_notification_category?
    return true if %w[text both].include?(notification_category) &&
                   welcome_sms_sent_at.nil?
    return true if %w[email both].include?(notification_category) &&
                   welcome_email_sent_at.nil?
  end
end

app/controllers/guests_controller.rb
# frozen_string_literal: true

# guests controller
class GuestsController < ApplicationController
  def index
    set_event
    @guests = @event.guests
  end

  def new
    set_event
    @guest = Guest.new
  end

  def create
    set_event
    @guest = @event.guests.build(guest_params)
    if @guest.save
      redirect_to event_guests_path(@event),
                  notice: "#{@guest.full_name} was saved successfully."
    else
      render :new
    end
  end

  def edit
    set_event
    @guest = Guest.find(params[:id])
  end

  def update
    set_event
    @guest = Guest.find(params[:id])
    if @guest.update(guest_params)
      redirect_to event_guests_path(@event),
                  notice: "#{@guest.full_name} was updated successfully."
    else
      render :edit
    end
  end

  def destroy
    set_event
    @guest = Guest.find(params[:id])
    @guest.destroy
    redirect_to(
      event_guests_path(@event),
      notice: "#{@guest.full_name} was deleted successfully"
    )
  end

  private

  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :email,
                                  :phone_number, :notification_category)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/views/guests/_form.html.erb
<%= form_for @guest, url: url, class: "form-horizontal" do |f| %>
  <%= render "shared/alert", invalid_object: @guest, name: "guest" %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: "form-control",  pattern: "[0-9]+", minlength: "10", maxlength: "10" %>
    <small class="form-text text-muted">Do not add leading 1.</small>
  </div>

  <div class="form-group">
    <%= f.label :notification_category %>
    <%= f.select :notification_category, [:text, :email, :both], {}, class: "form-control" %>
  </div>

  <%= f.submit "Save", class: "btn btn-primary" %>
  <%= link_to "Cancel", event_guests_path(@event), class: "btn btn-secondary" %>
<% end %>

app/views/guests/_guest.html.erb
<div class="card">
  <div class="card-header" id="heading-<%= guest.id %>">
    <h5 class="mb-0">
      <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-<%= guest.id %>" aria-expanded="false" aria-controls="collapse-<%= guest.id %>">
        <%= guest.full_name %>
      </button>
    </h5>
  </div>
  <div id="collapse-<%= guest.id %>" class="collapse" aria-labelledby="heading-<%= guest.id %>" data-parent="#accordion">
    <div class="card-body">
      <div class="row">
        <div class="col-12 col-lg-4 text-truncate">
          <strong>Email:</strong> <%= guest.email %>
        </div>
        <div class="col-12 col-lg-3">
          <strong>Phone:</strong> <%= guest.pretty_phone_number %>
        </div>
        <div class="col-12 mb-2 mb-lg-0 col-lg-3">
          <strong>Notification type:</strong> <%= guest.pretty_notification_category %>
        </div>
        <div class="col-12 col-lg-2">
          <span class="col-3 text-center">
            <%= link_to "", edit_event_guest_path(event, guest), class: "fa fa-lg fa-pencil" %>
          </span>
          <span class="col-3 text-center">
            <%= link_to "", destroy_url, method: :delete, data: { confirm: "Are you sure?" }, class: "fa fa-lg fa-trash" %>
          </span>
          <span class="col-3 text-center"></span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/guests/edit.html.erb
<% breadcrumb :edit_guest, @event, @guest %>

<h1>Edit <%= @guest.full_name %></h1>

<div class="mt-3">
  <%= render "guests/form", url: event_guest_path(@event, @guest) %>
</div>

app/views/guests/index.html.erb
<% breadcrumb :guests, @event %>

<h1><%= @event.nickname %> Guests</h1>

<div class="mb-3">
  <%= link_to "Add Guests to this Event", new_event_guest_path(@event) %>
</div>

<div id="accordion">
  <% @guests.each do |guest| %>
    <%= render "guests/guest", event: @event, guest: guest, destroy_url: event_guest_path(@event, guest) %>
  <% end %>
</div>

app/views/guests/new.html.erb
<% breadcrumb :new_guest, @event %>

<h1>Add a Guest</h1>

<div class="mt-3">
  <%= render "guests/form", url: event_guests_path(@event) %>
</div>