config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
    patch "/users/confirmation" => "confirmations#confirm"
  end
  resources :events, only: %i[index show new create edit update] do
    resources :notifications, only: %i[new create] do
      get :preview_email, on: :collection
    end
    resources :experiences, only: %i[index new create edit update] do
      resources :notifications, only: %i[show edit update] do
        get :preview_email, on: :member
        resources :guests_notifications, only: %i[new create destroy]
      end
    end
    resources :guests, only: %i[index new create edit update destroy]
  end
  resource :short_url, only: :show
  resource :end_user_agreement, only: :show
  resource :privacy_policy, only: :show
  resource :terms_and_conditions, only: :show
  get 'contact_us', to: 'contacts#new'
  resources :contacts, only: [:create]
  root to: 'events#index'
end

app/models/notification.rb
# frozen_string_literal: true

# notification for experiences
class Notification < ApplicationRecord
  belongs_to :experience

  has_many :guests_notifications, dependent: :destroy
  has_many :guests, through: :guests_notifications,
                    source: :guest

  validates :sms_body, :email_body, presence: true

  def sms_link
    return nil unless sms_body.include? 'http://bit.ly'
    short_link = %r{http:\/\/bit.ly\/.+$}.match(sms_body)[0]
    Bitly.client.expand(short_link).long_url
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

# notifications controller
class NotificationsController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
    @notification = Notification.new(sms_body: '', email_body: '')
  end

  def create
    @event = Event.find(params[:event_id])
    @notification = experience.build_notification(notification_params)
    if @notification.save
      Tasks::Notifier.send_to_all_now(@notification)
      redirect_to event_path(@event), notice: 'Sent successfully.'
    else
      render :new
    end
  end

  def show
    set_instance_variables
  end

  def edit
    set_instance_variables
    @sms_link = helpers.sanitize(@notification.sms_link)
  end

  def update
    set_instance_variables
    if @notification.update(notification_params)
      redirect_to(
        event_experience_notification_path(@event, @experience, @notification),
        notice: "#{@experience.name} notification was updated successfully."
      )
    else
      render :edit
    end
  end

  def preview_email; end

  private

  def notification_params
    params.require(:notification).permit(:sms_body, :email_body)
  end

  def set_instance_variables
    @experience = Experience.find(params[:experience_id])
    @event = @experience.event
    @notification = Notification.find(params[:id])
    @guests_notifications = @notification.guests_notifications
  end

  def experience
    # create experience and set it beyond the time needed for next nofitication
    ten_hours_ago = Time.zone.now - 10 * 60 * 60
    @experience ||= Experience.create!(
      name: "Send now! #{Time.zone.now}",
      occurs_at: ten_hours_ago,
      notification_offset: 60,
      event: @event
    )
  end
end

app/views/notifications/_form.html.erb
<%= form_for @notification, url: url, class: "form-horizontal" do |f| %>
  <%= render "shared/alert", invalid_object: @notification, name: "notification" %>

  <div class="form-group">
    <%= f.label :sms_body %>
    <i type="button" class="fa fa-question-circle text-muted" data-toggle="tooltip" data-placement="top" title="We recommend SMS messages stay under 160 characters to ensure all guests receive the full message."></i>
    <%= f.text_area :sms_body, class: "form-control", onkeyup: "countChar(this)" %>
    <small id="sms-character-count-help" class="form-text text-muted">
      <%= @notification.sms_body.length %> characters
    </small>
    <small class="form-text text-muted" id="sms-full-link">
      <% if @sms_link %>
        Current SMS link: <%= h @sms_link %>
      <% end %>
    </small>
  </div>

  <div class="form-group">
    <label for="notification_sms_link">SMS Link</label>
    <i type="button" class="fa fa-question-circle text-muted" data-toggle="tooltip" data-placement="top" title="If you'd like to have a link in your SMS, enter it here. We will shorten it for you and append it to the SMS body."></i>
    <input id="notification_sms_link" name="sms-link" type="text" class="form-control">
    <button type="button" class="btn btn-outline-secondary" onclick="appendSmsLink()">Append link to SMS body</button>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <%= f.label :email_body %>
        <small class="form-text text-muted">
          This editor support Markdown. For a tutorial on Markdown go <a href="http://commonmark.org/help/" target="_blank">here</a>
        </small>
        <%= f.text_area :email_body, onkeyup: "renderEmailPreview(this)", class: "form-control", rows: "10" %>
      </div>
    </div>

    <div class="col-6">
      <label>Email Preview</label>
      <small class="form-text text-muted">
        This is a preview of what your email will look like.
      </small>
      <div class="card">
        <div class="card-body" id="email-body-preview">
          <%= render "notifications/preview", email_body: @notification.email_body %>
        </div>
      </div>
    </div>
  </div>

  <%= f.submit "Save", class: "btn btn-primary" %>
  <%= link_to "Cancel", event_path(@event), class: "btn btn-secondary"  %>
<% end %>

app/views/notifications/_preview.html.erb
<%= simple_format(markdown(email_body)) %>

app/views/notifications/edit.html.erb
<% breadcrumb :edit_notification, @event, @experience, @notification %>

<h1>Edit <%= @experience.name %> Notification</h1>

<div class="mt-3">
  <%= render "notifications/form", url: event_experience_notification_path(@event, @experience, @notification) %>
</div>

app/views/notifications/new.html.erb
<% breadcrumb :new_notification, @event, @notification %>

<h1>Send notification to all guests now</h1>

<div class="mt-3">
  <%= render "notifications/form", url: event_notifications_path(@event, @notification) %>
</div>

app/views/notifications/preview_email.js.erb
$("#email-body-preview").html(
  "<%= escape_javascript(render partial: 'notifications/preview', locals: { email_body: params[:email_body] }) %>"
);

app/views/notifications/show.html.erb
<% breadcrumb :notification, @event, @experience, @notification %>

<h1>Notification for <%= @experience.name %></h1>

<div class="text-muted">
  <div>
    <%= @experience.pretty_occurs_at %> |
    <%= link_to "Edit notification timing", edit_event_experience_path(@event, @experience) %>
  </div>
  <div>
    Sent <%= @experience.notification_offset %> minutes before
  </div>
</div>

<hr>

<h2>Notification</h2>

<div class="mb-3">
  <%= link_to "Edit notification body", edit_event_experience_notification_path(@event, @experience, @notification) %>
</div>

<h3>SMS Body</h3>

<div class="card mb-3">
  <div class="card-body">
    <%= @notification.sms_body %>
  </div>
</div>

<h3>Email Body</h3>

<div class="card mb-3">
  <div class="card-body">
    <%= render "notifications/preview", email_body: @notification.email_body %>
  </div>
</div>

<hr>

<h2>Guests</h2>

<div class="mb-3">
  <%= link_to "Add Guests to this Experience", new_event_experience_notification_guests_notification_path(@event, @experience, @notification) %>
</div>

<div id="accordion">
  <% @guests_notifications.each do |guests_notification| %>
    <%= render "guests/guest", event: @event, guest: guests_notification.guest, destroy_url: event_experience_notification_guests_notification_path(@event, @experience, @notification, guests_notification) %>
  <% end %>
</div>