config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
    patch "/users/confirmation" => "confirmations#confirm"
  end
  resources :events, only: %i[index show new create edit update] do
    resources :notifications, only: %i[new create] do
      get :preview_email, on: :collection
    end
    resources :experiences, only: %i[index new create edit update] do
      resources :notifications, only: %i[show edit update] do
        get :preview_email, on: :member
        resources :guests_notifications, only: %i[new create destroy]
      end
    end
    resources :guests, only: %i[index new create edit update destroy]
  end
  resource :short_url, only: :show
  resource :end_user_agreement, only: :show
  resource :privacy_policy, only: :show
  resource :terms_and_conditions, only: :show
  get 'contact_us', to: 'contacts#new'
  resources :contacts, only: [:create]
  root to: 'events#index'
end

app/models/event.rb
# frozen_string_literal: true

# top-level event (i.e. wedding)
class Event < ApplicationRecord
  has_many :experiences, dependent: :destroy
  has_many :guests, dependent: :destroy
  has_many :users_events, dependent: :destroy
  has_many :users, through: :users_events, source: :user, dependent: :destroy

  validates :name, :occurs_at, :organizer, presence: true

  default_scope { order(occurs_at: :asc) }

  before_save :use_name_as_nickname

  def welcome_email
    "Hello,\n\n#{organizer} has signed you up for notifications for #{name}."
  end

  def welcome_sms
    "#{organizer} has signed you up for notifications for #{name}."
  end

  private

  def use_name_as_nickname
    return if nickname.present?
    self.nickname = name
    save
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# events controller
class EventsController < ApplicationController
  def index
    @events = current_user.events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      UsersEvent.create(user: current_user, event: @event)
      redirect_to events_path,
                  notice: "#{@event.nickname} was created successfully."
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_path,
                  notice: "#{@event.nickname} was updated successfully."
    else
      render :edit
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :occurs_at, :nickname, :organizer)
  end
end

app/views/events/_form.html.erb
<%= form_for @event, url: url, class: "form-horizontal" do |f| %>
  <%= render "shared/alert", invalid_object: @event, name: "event" %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <small class="form-text text-muted">How the event will be identified to guests in notifications</small>
  </div>

  <div class="form-group">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, class: "form-control" %>
    <small class="form-text text-muted">Optional name for quick identification. Used only in EventBeacon.</small>
  </div>

  <div class="form-group">
    <%= f.label :occurs_at %>
    <%= f.datetime_select :occurs_at %>
  </div>

  <div class="form-group">
    <%= f.label :organizer %>
    <%= f.text_field :organizer, class: "form-control" %>
    <small class="form-text text-muted">How you will be identified to guests in notifications</small>
  </div>

  <%= f.submit "Save", class: "btn btn-primary" %>
  <%= link_to "Cancel", events_path, class: "btn btn-secondary" %>
<% end %>

app/views/events/edit.html.erb
<% breadcrumb :edit_event, @event %>

<h1>Edit <%= @event.nickname %></h1>

<div class="mt-3">
  <%= render "events/form", url: event_path(@event) %>
</div>

app/views/events/index.html.erb
<h1>Events</h1>

<div class="mb-3">
  <%= link_to "Add", new_event_path %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date/Time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.nickname, event_path(event) %></td>
        <td><%= event.occurs_at.strftime('%m/%d/%Y %I:%M %P') %></td>
        <td><%= link_to "", edit_event_path(event), class: "fa fa-pencil" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<% breadcrumb :new_event %>

<h1>Add an event</h1>

<div class="mt-3">
  <%= render "events/form", url: events_path %>
</div>

app/views/events/show.html.erb
<% breadcrumb :event, @event %>

<h1><%= @event.nickname %></h1>

<div class="pt-2">
  <div><%= link_to "Guests", event_guests_path(@event) %></div>
  <div><%= link_to "Experiences", event_experiences_path(@event) %></div>
  <hr>
  <div><%= link_to "Send Notification to All Guests Now", new_event_notification_path(@event) %></div>
</div>