config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
    patch "/users/confirmation" => "confirmations#confirm"
  end
  resources :events, only: %i[index show new create edit update] do
    resources :notifications, only: %i[new create] do
      get :preview_email, on: :collection
    end
    resources :experiences, only: %i[index new create edit update] do
      resources :notifications, only: %i[show edit update] do
        get :preview_email, on: :member
        resources :guests_notifications, only: %i[new create destroy]
      end
    end
    resources :guests, only: %i[index new create edit update destroy]
  end
  resource :short_url, only: :show
  resource :end_user_agreement, only: :show
  resource :privacy_policy, only: :show
  resource :terms_and_conditions, only: :show
  get 'contact_us', to: 'contacts#new'
  resources :contacts, only: [:create]
  root to: 'events#index'
end

app/views/layouts/_alert.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <span class="notice"><%= notice %></span>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <span class="alert"><%= alert %></span>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom" style="min-height: 60px; background-color: #f5f5f5; padding-top: 15px;">
  <div class="container">
    <span>&copy; EventBeacon 2018</span> |
    <%= link_to "Contact us", contact_us_path %> |
    <%= link_to "Privacy Policy", privacy_policy_path %> |
    <%= link_to "Terms and Conditions", terms_and_conditions_path %> |
    <%= link_to "End-User License Agreement", end_user_agreement_path %>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <a class="navbar-brand" href="/">Event Beacon</a>
  <% if current_user %>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" rel="nofollow" data-method="delete"
           href="/users/sign_out">
          Log out
        </a>
      </li>
    </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Event Beacon</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="margin-bottom: 70px">
    <div class="container-fluid">
      <%= render "layouts/nav" %>

      <div class="container">
        <div class="mb-2">
          <%= breadcrumbs pretext: "", separator: " &rsaquo; " %>
        </div>
        <%= render "layouts/alert" %>
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>